### ISSUE TITLE
Panic if .config doesn't exist

### ISSUE THREAD

**Issue by jacobeva** [Zeos-ctrl/newsman#2]
The program panics if the .config folder doesn't exist in the user's home directory. It should create the newsman folder recursively on first setup.

**Comment by Zeos-ctrl** [comment]
Ill add a check to see if a .config file exists

**Comment by Zeos-ctrl** [comment]
adding this code in next commit

let home: PathBuf = dirs::home_dir().expect("cannot get home dir");
match std::fs::read_dir(format!("{}/.config", &home.display())) {
        Ok(_) => debug!(".config exists continuing setup"),
        Err(_) => {
            debug!(".config not found creating it now");
            std::fs::create_dir(format!("{}/.config", &home.display()))
                .expect("failed to make .config")
        }
    }
