### ISSUE TITLE
Poor defaults in newsman.toml

### ISSUE THREAD

**Issue by jacobeva** [Zeos-ctrl/newsman#3]
The defaults given in newsman.toml have no comments and are not typically expected values, e.g. smtp_username has "default" instead of an actual email. Comments and more clear defaults should be added to this file.

**Comment by Zeos-ctrl** [comment]
Agreed, ill change the values to more realistic values.

Config {
            url: format!("mysql://root:password@localhost/newsman"),
            dir: format!("~/.config/newsman/newsletters/"),
            smtp_username: format!("newsletter@example.com"),
            smtp_password: format!("example"),
            sender: format!("newsletter@example.com"),
            relay: format!("mail.example.com"),
            interval: 0
        }
does this look better?

**Comment by jacobeva** [comment]
Remove the format! from each line and you're good.

**Comment by Zeos-ctrl** [comment]
the format!() macro is needed to convert from &str to String for the struct

**Comment by jacobeva** [comment]
ah okay, go ahead then!

**Comment by Zeos-ctrl** [comment]
fixed in commit#39146b3
