### ISSUE TITLE
Duplicate detection

### ISSUE THREAD

**Issue by jacobeva** [Zeos-ctrl/newsman#4]
If newsman is asked to add an email, it should first check if this email exists in the mailing_list table, otherwise unintended behaviour may occur.

**Comment by Zeos-ctrl** [comment]
I'll add a check to make sure if an email already exists the user is notified.

**Comment by Zeos-ctrl** [comment]
i just realised there's no duplicate protection for jobs aswell so im going to add that change to the job functions aswell

**Comment by Zeos-ctrl** [comment]
fixed in commit#39146b3
